### ISSUE TITLE
Document community-created custom playsets

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#472]
There's some community folks who have created custom playsets for "common" scenarios that might be of interest to other folks. It  would be nice to have a page in our docs dedicated to that, and linked to appropriately from various playset doc pages.

Some examples:

```
---
name: Starforged with more Sundered Isles
ironvault:
  playset:
    type: globs
    lines:
      - "@include(starforged)"
      - asset:sundered_isles/** [starforged.recommended=true]
      - oracle_rollable:sundered_isles/misc**
      - oracle_rollable:sundered_isles/overland**
      - oracle_rollable:sundered_isles/weather**
      - oracle_rollable:sundered_isles/treasure**
      - "!oracle_rollable:sundered_isles/misc/local**"
iron-vault-kind: campaign
---
```

```
---
name: Starforged Ironsworn
ironvault:
  playset:
    type: globs
    lines:
      - "@include(sundered_isles__assets_all)"
      - oracle_rollable:classic**
      - oracle_rollable:delve**
      - move:delve/**
      - asset:classic/**
      - "!move:classic/**"
      - "!asset:starforged/** [core.technological=true]"
      - "!asset:sundered_isles/** [core.technological=true]"
iron-vault-kind: campaign
---
```
